default_pulling_interval: 10
token: "MFc21oKGzrtQuXoPg1iVowAKH0pHBA45saiBiePc"
plugins:
  - type: postgresql
    name: test_db
    description: "" # Optional string
    database: postgres
    host: 172.20.0.5
    port: 5432
    user: postgres
    password: !ENV ${MY_POSTGRES_PASSWORD}
#  - type: postgresql
#    name: health_db
#    description: "" # Optional string
#    database: health
#    host: 127.0.0.1
#    port: 5432
#    user: postgres
#    password: !ENV ${MY_POSTGRES_PASSWORD}
