version: "3.3"
services:
  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5433:5432

  odd-platform:
    image: ghcr.io/opendatadiscovery/odd-platform:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    ports:
      - 1234:8080

  odd-collector:
    image: ghcr.io/opendatadiscovery/odd-collector:0.1.62 # "ghcr.io/opendatadiscovery/odd-collector:latest" failed, use version 0.1.62
    restart: always
    volumes:
      - ./config/collector_config.yaml:/app/collector_config.yaml
    environment:
      - PLATFORM_HOST_URL=${PLATFORM_HOST_URL}
      - SAMPLE_POSTGRES_HOST=sample-postgresql
      - SAMPLE_POSTGRES_USER=${SAMPLE_POSTGRES_USER}
      - SAMPLE_POSTGRES_DATABASE=${SAMPLE_POSTGRES_DATABASE}
      - SAMPLE_POSTGRES_PASSWORD=${SAMPLE_POSTGRES_PASSWORD}
      - MY_POSTGRES_USER=postgres
      - MY_POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}
      - MY_POSTGRES_DATABASE=${MY_POSTGRES_DATABASE}
